safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Mohammad Ghasempour"
description: ""
baseurl: ""
url: "https://aghsempour.github.io/" # replace by your site's url
twitter_username: aminejazz
github_username:  aminGhasempour # (your name)
orcid_username: 
linkedin_username: 
accent: "#f7f7e6" # accent color for blog column

author: "Mohammad Ghasempour"
email: "aghasempour@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
