safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Mohammad Ghasempour"
description: ""
baseurl: ""
url: "https://aghsempour.github.io/" # replace by your site's url
twitter_username: aminejazz
github_username:  aminGhasempour # (your name)
orcid_username: 0000-0003-0633-0177
linkedin_username: mohammad-ghasempour-230692a0
accent: "#ffffff" # accent color for blog column
picture: 1698536759069.jfif

author: "Mohammad Ghasempour"
email: "aghasempour@gmail.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
